baseURL = 'https://lknuth.dev/'
languageCode = 'en-us'
title = 'Lukas Knuth // Developer'
copyright = "Lukas Knuth"

theme = 'cactus'
enableInlineShortcodes = true

[[menu.main]]
name = "Writings"
url = "/writings"
weight = 1
[[menu.main]]
name = "About"
url = "/about"
weight = 10
[[menu.main]]
name = "CV"
url = "/cv"
weight = 11
[[menu.main]]
name = "Imprint"
url = "/imprint"
weight = 50

[params]
mainSection = "writings"
postsOnHomePage = 5
tagsOverview = false
showProjectsList = true

[[params.social]]
name = "github"
link = "https://github.com/LukasKnuth"

[[params.social]]
name = "stack-overflow"
link = "https://stackoverflow.com/users/717341/lukas-knuth"

[[params.social]]
name = "linkedin"
link = "https://www.linkedin.com/in/lukas-knuth-1b0b18128/"

[markup]
	[markup.goldmark.renderer]
	 # allow HTLM tags in markdown
		unsafe = true
  [markup.highlight]
    codeFences = true
	guessSyntax = false
	tabWidth = 2
	style = "gruvbox"