baseURL = "https://lknuth.dev/"
languageCode = "en-us"
title = "Lukas Knuth // Software Engineer"
copyright = "Lukas Knuth"

#theme = 'neon_noir'
disableKinds = ["taxonomy"]
enableInlineShortcodes = true

[[menu.main]]
name = "Writings"
url = "/writings"
weight = 1
[[menu.main]]
name = "About"
url = "/about"
weight = 10
[[menu.main]]
name = "CV"
url = "/cv"
weight = 11

[params]
shortTitle = "Lukas Knuth // SWE"
mainSection = "writings"
mainSectionTitle = "Writings"
postsOnHomePage = 5
tagsOverview = false
dateFormat = "2006-01-02"

[[params.social]]
name = "github"
link = "https://github.com/LukasKnuth"

[[params.social]]
name = "stackoverflow"
link = "https://stackoverflow.com/users/717341/lukas-knuth"

[[params.social]]
name = "linkedin"
link = "https://www.linkedin.com/in/lukas-knuth-1b0b18128/"

[markup]

[markup.goldmark.renderer]
# allow HTLM tags in markdown
unsafe = true

[markup.highlight]
codeFences = true
guessSyntax = false
tabWidth = 2
style = "catppuccin-latte"

# Configure Build to work with Tailwind v4.
# Mostly taken from https://github.com/bep/hugo-testing-tailwindcss-v4/tree/main/tailwindcss-cli-defer
# See also https://gohugo.io/functions/css/tailwindcss/ and https://gohugo.io/functions/templates/defer/
[module]

[module.hugoVersion]
min = "0.128.0"

[[module.mounts]]
source = "assets"
target = "assets"

[[module.mounts]]
source = "content"
target = "content"

[[module.mounts]]
source       = "hugo_stats.json"
target       = "assets/notwatching/hugo_stats.json"
disableWatch = true

[build.buildStats]
enable = true

[[build.cachebusters]]
source = "assets/notwatching/hugo_stats\\.json"
target = "css"

