name: github pages

on:
  push

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    env:
      # Skips any "devDepenency" packages and runs everything in prod mode.
      NODE_ENV: production
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff # v3.0.0
        name: Install just
      - name: Install fonttools
        run: pip install fonttools brotli
      - uses: peaceiris/actions-hugo@75d2e84710de30f6ff7268e08f310b60ef14033f # v3.0.0
        name: Install Hugo
        with:
          hugo-version: '0.147.8'
          extended: true
      - name: Install Node dependencies
        run: npm ci
      - name: Build
        run: just build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: lknuth.dev
